# Generated by Django 5.2.6 on 2025-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_category_product_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show, 1-hidden'),
        ),
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default, 1-trending'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show, 1-hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default, 1-trending'),
        ),
    ]
